# local compose file for testing

services:
  wallet:
    image: antonpegov/zeropool-frontend:latest
    container_name: zeropool-wallet-dev
    restart: always
    ports:
      - '80:80'
    environment:
      - REACT_APP_TOKEN=eth
      - REACT_APP_PUBLIC_URL=/
      - REACT_APP_NETWORK=ethereum
      - REACT_APP_NETWORK_NAME=Sepolia
      - REACT_APP_NETWORK_FAUCET=https://sepoliafaucet.com/
      - REACT_APP_RPC_URL=https://sepolia.rpc.zeropool.network
      - REACT_APP_RELAYER_URL=https://sepolia.testnet.relayer.v2.zeropool.network
      - REACT_APP_TOKEN_ADDRESS=0x25004028Dd2743FF487454eAB2216d3495667189
      - REACT_APP_CONTRACT_ADDRESS=0xEcbD5fabA99139B2cA25f19B568fF74991a01eD3
      - REACT_APP_TRANSACTION_URL='https://sepolia.etherscan.io/tx/{{hash}}'
    volumes:
      - ./static/assets:/usr/share/nginx/html/assets
