#!/usr/bin/env bash
# MNEMONIC matrix slogan main great dove charge mesh help month boss area trial
# faucet https://faucet.poa.network/
# block explorer https://blockscout.com/poa/sokol

export REACT_APP_EVM_RPC='https://xdai.testnet.zeropool.dev/'
export REACT_APP_RELAYER_URL='https://xdai.testnet.relayer.v2.zeropool.network'
export REACT_APP_TOKEN_ADDRESS='0x520Df8b53b5a24A4A2BE72Bfe315c1022392CfA7'
export REACT_APP_CONTRACT_ADDRESS='0xa263d87A178d7b244C688ef8cc2af592167f85e2'
npm i && npm start
