#!/usr/bin/env bash
# chainID: 1313161555
# symbol: ETH
# faucet https://testnet.aurora.dev/faucet
# explorer https://explorer.testnet.aurora.dev/

export REACT_APP_EVM_RPC='https://aurora.testnet.zeropool.dev/'
export REACT_APP_RELAYER_URL='https://aurora.testnet.relayer.v2.zeropool.network'
export REACT_APP_TOKEN_ADDRESS='0xcda2B3489aCDB31A428bd33fcAEE5c7c50919b35'
export REACT_APP_CONTRACT_ADDRESS='0xC40Dd5B1250F4A7E70E1823d1D8eAbEA247cB1B3'
npm i && npm start
